name: Build and Deploy WebGL

on:
  push:
    branches: [ main ]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Activate Unity
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.0f1  # or whatever your project uses
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      # Build for WebGL
      - name: Build WebGL
        uses: game-ci/unity-builder@v3
        with:
          targetPlatform: WebGL
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL/WebGL
