name: Request Unity Manual Activation

on:
  workflow_dispatch:
  push:
    paths: [.github/workflows]

jobs:
  requestManualActivation:
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        uses: game-ci/unity-request-activation@v2
        with:
          unityVersion: 2019.3.0f6

      - name: Upload .alf file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: UnityActivationFile
          path: unity_v2019.x.alf
