name: Request Unity Manual Activation

on:
  workflow_dispatch:
  push:
    paths: [.github/workflows]

jobs:
  requestManualActivation:
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        uses: game-ci/unity-return-license@v2
        with:
          unityVersion: 2019.3.0f6
