name: Generate Unity Manual Activation File (No Actions)

on:
  workflow_dispatch:

jobs:
  generate-alf:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Unity Docker image
        run: docker pull unityci/editor:ubuntu-2019.4.40f1-base-0

      - name: Generate .alf license file
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            unityci/editor:ubuntu-2019.4.40f1-base-0 \
            unity-editor \
              -quit \
              -batchmode \
              -createManualActivationFile \
              -logFile /dev/stdout
              
          echo "::notice title=Download Manual Activation File::.alf file generated. You must now manually download it from the workflow run artifacts."

      - name: List generated files
        run: ls -lh

      - name: Base64 encode .alf so you can copy/paste it from logs
        run: |
          base64 Unity_v2019.x.alf > encoded_alf.txt
          echo "::group::Base64-encoded .alf (copy this and decode it locally)"
          cat encoded_alf.txt
          echo "::endgroup::"
