name: Generate Unity Manual Activation File

on:
  workflow_dispatch:

jobs:
  generate-alf:
    runs-on: ubuntu-latest
    steps:
      - name: Download Unity 2019.4.40f1 Editor Docker image
        run: |
          docker pull unityci/editor:ubuntu-2019.4.40f1-base-0

      - name: Generate .alf activation request file
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/project \
            unityci/editor:ubuntu-2019.4.40f1-base-0 \
            unity-editor \
              -quit \
              -batchmode \
              -createManualActivationFile \
              -logFile /dev/stdout

      - name: Upload .alf file
        uses: actions/upload-artifact@v3
        with:
          name: Unity_Activation_Request_File
          path: Unity_v2019.x.alf
